from dotenv import load_dotenv
from typing import TypedDict,Annotated
from langchain.chat_models import init_chat_model
from langchain.agents import create_agent
from langgraph.graph import StateGraph,START,add_messages,END
import os
from langgraph.checkpoint.postgres import PostgresSaver
from langchain_core.messages import AnyMessage,HumanMessage,SystemMessage,ToolMessage
from app.prompt import MODEL_SYSTEM_PROMPT
from app.config import (GEMINI_MODEL,MODEL_PROVIDER)
from app.tools.tools import tools

load_dotenv()

DB_URL=os.getenv('DB_URL')

#create state
class MessageState(TypedDict):
    messages:Annotated[list[AnyMessage],add_messages]



#model
model=init_chat_model(model=GEMINI_MODEL,model_provider=MODEL_PROVIDER)
agent=create_agent(model=model,tools=tools,state_schema=MessageState)



#create node
def chat_node(state: MessageState) -> MessageState:
    """Generate a response using the conversation history."""

    messages = [
        SystemMessage(content=MODEL_SYSTEM_PROMPT),
        *state["messages"],
    ]

    answer = agent.invoke({
        "messages": messages,
    })
    return {
        "messages": answer["messages"]
    }



graph=StateGraph(MessageState)

#create node
graph.add_node("chat_node",chat_node)

#add edge
graph.add_edge(START,"chat_node")
graph.add_edge("chat_node",END)

checkpointer_cm = PostgresSaver.from_conn_string(DB_URL)
checkpointer = checkpointer_cm.__enter__()
checkpointer.setup()
builder = graph.compile(
    checkpointer=checkpointer
)

def test_agent(question: str, user_id: str):

    config = {
        "configurable": {
            "thread_id": user_id
        }
    }

    # Get state BEFORE this request
    previous_state = builder.get_state(config)
    previous_messages = previous_state.values.get("messages", [])
    previous_count = len(previous_messages)

    output = builder.invoke(
        {
            "messages": [
                HumanMessage(content=question)
            ],
        },
        config=config,
    )

    messages = output["messages"]

    # Only messages generated by this request
    current_messages = messages[previous_count:]

    # Tool outputs for this request
    retrieval_context = [
        message.content
        for message in current_messages
        if isinstance(message, ToolMessage)
    ]

    # Tool calls for this request
    tools_called = []

    for message in current_messages:
        if getattr(message, "tool_calls", None):
            for tool_call in message.tool_calls:
                tools_called.append({
                    "name": tool_call["name"],
                    "args": tool_call.get("args", {}),
                })

    return {
        "answer": messages[-1].content,
        "retrieval_context": retrieval_context,
        "tools_called": tools_called,
    }



if __name__=="__main__":
    result = test_agent(
        question="whats the company remote work policy?",
        user_id="test-agent-43",
    )
    print(result)
    # print(result['answer'][0]['text'])
    # print("Retrieval Context",result['retrieval_context'])
    # print("Tools Called",result['tools_called'])
    # print(result['answer'][0]['text'])
 
